### ISSUE TITLE
Furk Scraper - Removing %xx Characters From Query String

### ISSUE THREAD

**Issue by supafyn** [norris-addons/tknorris-beta-repo#2]
I was noticing in the furk scraper that any time you dealt with tv shows that had special characters in the show's title like "&" instead of the word "and" that the code for the scraper was simply translating the value to the appropriate html equivalent and passing this value into the query string and as a result causing no results to return since these html equivalent values are not present anywhere in the tv show title being searched.

Instead of translating these types of characters, I was looking for a solution where only these types of characters would be removed completely from the tv show title search portion and thus allow furk the opportunity to return any valid results. I was able to successfully modify the existing furk scraper to do this and tested it on the following tv shows to confirm results would now show where previously they had not:

CSI: Cyber
Young & Hungry
The Real O'Neals

I have attached my modifications and obviously hoping in a future update you could look this over and possibly incorporate some version of the change into the scraper so that manual manipulation each time an episode of these types of tv shows are watched can be minimized a bit more. For reference, the changes I made can be found on lines 103 and 187 to 188.

[furk_scraper.txt](https://github.com/norris-addons/tknorris-beta-repo/files/170808/furk_scraper.txt)

**Comment by supafyn** [comment]
So after running a few more use cases, I see my original solution was going to have issues with other tv shows such as:

Marvel's Agents of S.H.I.E.L.D.

because I was removing the needed periods for a successful search match due to the regex I had originally gone with. The solution to resolve this and to still address my issues with the other list of tv shows was simply to do the following replacement in the furk scraper:

Replace anywhere it said "urllib.quote_plus(" with "urllib.unquote_plus("

Found that by simply changing out just the library function being utilized that results could be consistently found when comparing SALTS to the Furk webpage result set.

Attaching the updated file for your review and comments.

[furk_scraper_lib_update.txt](https://github.com/norris-addons/tknorris-beta-repo/files/171013/furk_scraper_lib_update.txt)

**Comment by tknorris** [comment]
Thanks, I'll take a look and see what I can do to improve the matching for furk. I may not do the exact same thing for other reasons, but I'll take a look at it.
